name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 35.219.115.179
        username: ubuntu
        key: ${{ secrets.EC2_GCP_KEY }}
        script: |
          cd ~/myapp
          git pull origin master
          source venv/bin/activate
          nohup flask run --host=0.0.0.0 &
